### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by h6ppy** [GC-spigot/AdvancedSpawners#13]
Custom mobs are spawning very slow and in large amounts.

Custom mobs are not dropping items upon dying from fall damage.

 I am able to use our server settings to configure the spawn rates of normal spawnrates within the plugin, but when it comes to custom mobs, the spawn rates are not effected, also they are set to be spawning 1 mob per spawn, in the config as well as our server files. It is spawning 2-8 per spawn, and extremely slow.

Version - StellarSpigot 1.8

**Comment by GC-spigot** [comment]
It spawns using vanilla mob spawner speed, the amounts are configurable through config: https://prnt.sc/ro8iqu
The idea behind spawning slow and a lot at once is to reduce lag for the server. Since the mobs stack, having them spawn less often and in large numbers will reduce stress the server takes.

What goes for fall damage, I will add an option for this
