### ISSUE TITLE
Issues with mob stacking

### ISSUE THREAD

**Issue by KickSquareMC** [GC-spigot/AdvancedSpawners#271]
Hi,

I've been using AS on a production server for a bit now. I've encountered a good amount of issues though, especially with mob stacking.

- Fire aspect doesn't work on passive stacked mobs

-  Stacked mobs don't drop EXP based on the amount of mobs in a stack (1000x zombies don't drop 1000 times the XP a single zombie would, it's much lower. An option to toggle this if fixed would be good too)

- Stacked mobs sometimes "reincarnate" (after killing a stack) with full armor and drop x(however many mobs were in the stack) amounts of armor. For example, for a x5 skeleton the "reincarnated" mob drops x5 chestplates, etc.

**Comment by GC-spigot** [comment]
1st - Looking into it
2nd - will look into it as well
3rd - sounds like an issue with another plugin, since only you are reporting this. I fixed the part where they drop armor but it does sound like something else is causing mobs to respawn. You can post your info from `/as debug` and maybe I can look into it better.
