### ISSUE TITLE
[Issue] /as editor bug

### ISSUE THREAD

**Issue by sashawik** [GC-spigot/AdvancedSpawners#303]
Trying to use /as editor to create new mobs, but when i click Browse Textures all categories are empty and i got this error message in console

Spigot 1.17(Latest)
Plugin version : 3.4.3
Default config(Just downloaded plugin)
Local server
Debug link : https://pastebin.com/S7dgQ20z 

![unknown](https://user-images.githubusercontent.com/33094008/137598391-a02c9eb8-557b-4c87-a7dd-1c78bb68aab2.png)

**Comment by GC-spigot** [comment]
Is your server in offline mode?

**Comment by sashawik** [comment]
you mean this? 
![изображение](https://user-images.githubusercontent.com/33094008/137945101-91c63a93-15f9-4c7c-9a8d-7be22c07a762.png)

**Comment by sashawik** [comment]
any updates?

**Comment by sashawik** [comment]
tried to test it on host(not on local server) still same issue

**Comment by GC-spigot** [comment]
What server jar are you using? Spigot, Paper? Can you send your latest.log file? Thanks!

**Comment by CREEPERGAMER138** [comment]
hello I have the same problem I am using the server in disconnected mode I am on 1.18 and I tested the last 3 versions 3.6.2 3.6.1 3.6.0 and they all have the same error I am on a VPS with linux I am using spigot and here it is the server log 
[2021-12-18-3.log](https://github.com/GC-spigot/AdvancedSpawners/files/7747327/2021-12-18-3.log)
[latest.log](https://github.com/GC-spigot/AdvancedSpawners/files/7747329/latest.log)

and if you need a clean log I'll give it to you since we did a lot of tests

**Comment by GC-spigot** [comment]
Should be resolved
